package com.puduvandi.common.enums;

/**
 * Identifies which step of the physical bike handover an OTP is for.
 * Each purpose has a fixed "generated by" role and "validated by" role —
 * see HandoverOtpService for the exact mapping and resulting state transition.
 */
public enum HandoverPurpose {
    /** Self-pickup: customer generates, owner validates. CONFIRMED → RIDE_STARTED. */
    PICKUP_SELF,
    /** Partner delivery, owner→partner leg: partner generates, owner validates. DeliveryOrder CLAIMED → PICKED_UP. */
    PICKUP_PARTNER,
    /** Partner delivery, partner→customer leg: customer generates, partner validates. DeliveryOrder → DELIVERED; Booking → RIDE_STARTED. */
    RECEIVE_PARTNER,
    /** Self-pickup return: owner generates, customer validates. RETURN_REQUESTED → COMPLETED. */
    RETURN_SELF,
    /**
     * Partner delivery return, customer→partner leg: customer generates, partner validates.
     * Return-leg DeliveryOrder CLAIMED → PICKED_UP.
     */
    RETURN_TO_PARTNER,
    /**
     * Partner delivery return, partner→owner leg: owner generates, partner validates.
     * Return-leg DeliveryOrder → DELIVERED; Booking → COMPLETED.
     */
    RETURN_FINAL
}
